[workspace]
name = "yohane"
channels = ["conda-forge"]
platforms = [
    { name = "cu130-linux-64", platform = "linux-64", cuda = "13.0" },
    { name = "cu130-win-64", platform = "win-64", cuda = "13.0" },
    { name = "cu126-linux-64", platform = "linux-64", cuda = "12.6" },
    { name = "cu126-win-64", platform = "win-64", cuda = "12.6" },
    { name = "cpu-linux-64", platform = "linux-64" },
    { name = "cpu-win-64", platform = "win-64" },
    { platform = "osx-arm64", macos = "14.0" },
]

[dependencies]
python = "~=3.14.0"
ffmpeg = "~=9.0"

[pypi-dependencies]
yohane = { path = ".", editable = true }
yohane-cli = { path = "yohane-cli", editable = true }
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", branch = "6.0.0b4" }

[target."cu130-*".pypi-dependencies]
torch = { version = "==2.14.0", index = "https://download.pytorch.org/whl/cu130" }
torchaudio = { version = "==2.11.0", index = "https://download.pytorch.org/whl/cu130" }
torchcodec = { version = "==0.16.0", index = "https://download.pytorch.org/whl/cu130" }

[target."cu126-*".pypi-dependencies]
torch = { version = "==2.14.0", index = "https://download.pytorch.org/whl/cu126" }
torchaudio = { version = "==2.11.0", index = "https://download.pytorch.org/whl/cu126" }
torchcodec = { version = "==0.16.0", index = "https://download.pytorch.org/whl/cu126" }

[target."cpu-*".pypi-dependencies]
torch = { version = "==2.14.0", index = "https://download.pytorch.org/whl/cpu" }
torchaudio = { version = "==2.11.0", index = "https://download.pytorch.org/whl/cpu" }
torchcodec = { version = "==0.16.0", index = "https://download.pytorch.org/whl/cpu" }

[target."osx-*".pypi-dependencies]
torch = "==2.14.0"
torchaudio = "==2.11.0"
torchcodec = "==0.16.0"
