[workspace]
name = "yohane"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
python = "~=3.14.0"
ffmpeg = "~=8.0"

[pypi-dependencies]
yohane = { path = ".", extras = ["torch"], editable = true }
yohane-cli = { path = "yohane-cli", editable = true }
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", branch = "6.0.0b4" }
