[tool.poetry]
name = "yohane"
version = "0.1.0-dev"
description = ""
authors = ["NextFire <git@yuru.moe>", "Voltini <slimen3@hotmail.fr>"]
readme = "README.md"
repository = "https://github.com/Japan7/yohane"

[tool.poetry.scripts]
yohane = "yohane.__main__:main"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
torch = "^2.1.0"
torchaudio = "^2.1.0"
vocal-remover = {git = "https://github.com/Japan7/vocal-remover.git", rev = "00537bfe94f1575e9bae584a9e97220058b2ca9c"}
pysubs2 = "^1.6.1"
regex = "^2023.10.3"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.333"
ruff = "^0.1.3"
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.10"

[tool.ruff]
target-version = "py310"
