[tool.poetry]
name = "yohane"
version = "0.1.0"
description = ""
authors = ["NextFire <git@yuru.moe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
