[tool.poetry]
name = "yohane"
version = "2024.04.1"
description = ""
authors = ["NextFire <git@yuru.moe>", "Voltini <slimen3@hotmail.fr>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Japan7/yohane"

[tool.poetry.scripts]
yohane = "yohane:app"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
torch = { version = "2.2.2", optional = true }
torchaudio = { version = "2.2.2", optional = true }
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", rev = "24f34d7e0b92e0e8170acbbe3ef8e64b98b29f2b" }
pysubs2 = "1.6.1"
regex = "2023.12.25"
typer = { version = "0.11.1", extras = ["all"] }

[tool.poetry.extras]
torch = ["torch", "torchaudio"]

[tool.poetry.group.dev.dependencies]
pyright = "1.1.357"
ruff = "0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.10"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I"]
