[tool.poetry]
name = "yohane"
version = "2024.09.1-dev"
description = ""
authors = ["NextFire <git@yuru.moe>", "Voltini <slimen3@hotmail.fr>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Japan7/yohane"

[tool.poetry.scripts]
yohane = "yohane:app"

[tool.poetry.dependencies]
python = "^3.10"
torch = { version = "*", optional = true }
torchaudio = { version = "*", optional = true }
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", rev = "32f21722eeb59b6e125941bfff646b8e453707ee" }
pysubs2 = "1.7.3"
regex = "2024.7.24"
typer-slim = { version = "0.12.5", extras = ["standard"] }

[tool.poetry.extras]
torch = ["torch", "torchaudio"]

[tool.poetry.group.dev.dependencies]
pyright = "1.1.378"
ruff = "0.6.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.10"

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I"]
