[project]
name = "yohane"
version = "2024.10.4-dev"
description = "Forced alignment for karaokes"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10,<3.12"
dependencies = [
    "torch>=2.1,<3",
    "torchaudio>=2.1,<3",
    "vocal-remover",
    "pysubs2==1.7.3",
    "regex==2024.9.11",
    "typer-slim[standard]==0.12.5",
]

[tool.uv]
dev-dependencies = ["pyright==1.1.384", "ruff==0.6.9"]

[tool.uv.sources]
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", branch = "6.0.0b4" }

[project.scripts]
yohane = "yohane:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
pythonVersion = "3.10"
ignore = ["vendor"]
reportDeprecated = true

[tool.ruff]
exclude = ["notebook", "vendor"]

[tool.ruff.lint]
extend-select = ["I"]
