[tool.poetry]
name = "yohane"
version = "2023.11.12-dev"
description = ""
authors = ["NextFire <git@yuru.moe>", "Voltini <slimen3@hotmail.fr>"]
readme = "README.md"
repository = "https://github.com/Japan7/yohane"

[tool.poetry.scripts]
yohane = "yohane.__main__:cli"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
torch = {version = "^2.1.0", optional = true}
torchaudio = {version = "^2.1.0", optional = true}
vocal-remover = {git = "https://github.com/Japan7/vocal-remover.git", rev = "afdd4806b8c072dde953b20cc3346b29fa1e138e"}
pysubs2 = "^1.6.1"
regex = "^2023.10.3"
click = "^8.1.7"

[tool.poetry.extras]
torch = ["torch", "torchaudio"]

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.333"
ruff = "^0.1.3"
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.10"

[tool.ruff]
target-version = "py310"
