[tool.poetry]
name = "yohane"
version = "0.1.0"
description = ""
authors = ["NextFire <git@yuru.moe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
torchaudio = "^2.1.0"
numpy = "^1.26.1"
vocal-remover = {git = "https://github.com/Japan7/vocal-remover.git", rev = "00537bfe94f1575e9bae584a9e97220058b2ca9c"}
pysubs2 = "^1.6.1"
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
