trainer:
  max_epochs: 100
  callbacks:
    - class_path: EarlyStopping
      init_args:
        monitor: val_frame_accuracy
        mode: max
  logger:
    - class_path: TensorBoardLogger
      init_args:
        save_dir: lightning_logs
    - class_path: yohane_fa.logger.TrackioLogger
      init_args:
        project: yohane-fa

data:
  dataset_path: NextFire/karaoke-alignments
  batch_size: 8
  num_workers: 4
