trainer:
  max_epochs: 50
  log_every_n_steps: 10
  precision: bf16-mixed
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
  callbacks:
    - class_path: LearningRateMonitor
    - class_path: EarlyStopping
      init_args:
        monitor: val_frame_accuracy
        mode: max
  logger:
    - class_path: TensorBoardLogger
      init_args:
        save_dir: .
    - class_path: yohane_fa.logger.TrackioLogger
      init_args:
        project: yohane-fa

model:
  hidden_dim_multiplier: 16
  dropout: 0.05
  label_smoothing: 0.05

data:
  dataset_path: NextFire/karaoke-alignments
  load_from_cache_file: true
  batch_size: 8

optimizer:
  class_path: AdamW
  init_args:
    lr: 5e-4
    weight_decay: 1e-2

lr_scheduler:
  class_path: ReduceLROnPlateau
  init_args:
    monitor: val_loss
    factor: 0.5
    patience: 1
