[project]
name = "yohane-cli"
version = "0.1.0"
authors = [{ name = "NextFire", email = "git@yuru.moe" }]
dependencies = ["typer-slim[standard]==0.12.5"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
